package com.project.model;

public class Buyer extends User {
    private String buyerId; // e.g., B001 generated by DB
    private String preferredLocation;
    private Double budgetRange;
    private String purchaseTimeline;

    // Constructors
    public Buyer() {
        super();
    }

    public Buyer(String firstName, String lastName, String contactNumber, String address,
                 String email, String password, java.time.LocalDate dateOfBirth,
                 String preferredLocation, Double budgetRange, String purchaseTimeline) {
        super(firstName, lastName, contactNumber, address, email, password, dateOfBirth, "buyer");
        this.preferredLocation = preferredLocation;
        this.budgetRange = budgetRange;
        this.purchaseTimeline = purchaseTimeline;
    }

    // Getters and Setters
    public String getBuyerId() { return buyerId; }
    public void setBuyerId(String buyerId) { this.buyerId = buyerId; }

    public String getPreferredLocation() { return preferredLocation; }
    public void setPreferredLocation(String preferredLocation) { this.preferredLocation = preferredLocation; }

    public Double getBudgetRange() { return budgetRange; }
    public void setBudgetRange(Double budgetRange) { this.budgetRange = budgetRange; }

    public String getPurchaseTimeline() { return purchaseTimeline; }
    public void setPurchaseTimeline(String purchaseTimeline) { this.purchaseTimeline = purchaseTimeline; }
}