package com.project.model;

public class Seller extends User {
    private String sellerId; // e.g., S001 generated by DB
    private String businessRegistrationNumber;
    private String companyName;
    private String licenseNumber;

    // Constructors
    public Seller() {
        super();
    }

    public Seller(String firstName, String lastName, String contactNumber, String address,
                  String email, String password, java.time.LocalDate dateOfBirth,
                  String businessRegistrationNumber, String companyName, String licenseNumber) {
        super(firstName, lastName, contactNumber, address, email, password, dateOfBirth, "seller");
        this.businessRegistrationNumber = businessRegistrationNumber;
        this.companyName = companyName;
        this.licenseNumber = licenseNumber;
    }

    // Getters and Setters
    public String getSellerId() { return sellerId; }
    public void setSellerId(String sellerId) { this.sellerId = sellerId; }

    public String getBusinessRegistrationNumber() { return businessRegistrationNumber; }
    public void setBusinessRegistrationNumber(String businessRegistrationNumber) {
        this.businessRegistrationNumber = businessRegistrationNumber;
    }

    public String getCompanyName() { return companyName; }
    public void setCompanyName(String companyName) { this.companyName = companyName; }

    public String getLicenseNumber() { return licenseNumber; }
    public void setLicenseNumber(String licenseNumber) { this.licenseNumber = licenseNumber; }
}