package com.project.model;

import java.time.LocalDate;

public class User {
    private String userId; // e.g., U001 generated by DB
    private String firstName;
    private String lastName;
    private String contactNumber;
    private String address;
    private String email;
    private String password;
    private LocalDate dateOfBirth;
    private String role;
    private LocalDate registrationDate;

    // Constructors
    public User() {}

    public User(String firstName, String lastName, String contactNumber, String address,
                String email, String password, LocalDate dateOfBirth, String role) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.contactNumber = contactNumber;
        this.address = address;
        this.email = email;
        this.password = password;
        this.dateOfBirth = dateOfBirth;
        this.role = role;
        this.registrationDate = LocalDate.now();
    }

    // Getters and Setters
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getContactNumber() { return contactNumber; }
    public void setContactNumber(String contactNumber) { this.contactNumber = contactNumber; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public LocalDate getDateOfBirth() { return dateOfBirth; }
    public void setDateOfBirth(LocalDate dateOfBirth) { this.dateOfBirth = dateOfBirth; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public LocalDate getRegistrationDate() { return registrationDate; }
    public void setRegistrationDate(LocalDate registrationDate) { this.registrationDate = registrationDate; }

    // Method to check if user credentials match
    public boolean authenticate(String inputPassword) {
        return this.password != null && this.password.equals(inputPassword);
    }
}